title: Woodgrove Primary School
url: https://www.woodgrovepri.moe.edu.sg
favicon: /images/Badge.jpg
colors:
  primary-color: "#3c7536"
  secondary-color: "#6088b6"
  media-colors:
    - title: media-color-one
      color: "#f5a623"
    - title: media-color-two
      color: "#417505"
    - title: media-color-three
      color: "#1c42a0"
    - title: media-color-four
      color: "#f8751c"
    - title: media-color-five
      color: "#00838f"
description: Every Woodgrovian Shines - A Learner. A Contributor. A Leader with Character.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2aa2jwrrxgl47.amplifyapp.com
prod: https://master.d2aa2jwrrxgl47.amplifyapp.com
facebook-pixel: ""
shareicon: /images/Badge.jpg
is_government: false
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: resources
